name: deploy

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-n-publish:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Upgrade Setuptools
        run: pip install setuptools --upgrade
      - name: Build xtcocotools
        run: python setup.py sdist bdist_wheel --plat-name manylinux1_x86_64
      - name: Publish distribution 📦 to Test PyPI
        run: |
          pip install twine
          twine upload --repository testpypi dist/* -u __token__ -p ${{ secrets.TEST_PYPI_API_TOKEN }}
      - name: Publish distribution 📦 to PyPI
        if: startsWith(github.event.ref, 'refs/tags')
        run: |
          pip install twine
          twine upload dist/* -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}

  build-n-publish-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Upgrade Setuptools
        run: pip install setuptools --upgrade
      - name: Build xtcocotools
        run: python setup.py sdist bdist_wheel
      - name: Publish distribution 📦 to Test PyPI
        run: |
          pip install twine
          twine upload --repository testpypi dist/* -u __token__ -p ${{ secrets.TEST_PYPI_API_TOKEN }}
      - name: Publish distribution 📦 to PyPI
        if: startsWith(github.event.ref, 'refs/tags')
        run: |
          pip install twine
          twine upload dist/* -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}

  build-n-publish-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Upgrade Setuptools
        run: pip install setuptools --upgrade
      - name: Build xtcocotools
        run: python setup.py sdist bdist_wheel
      - name: Publish distribution 📦 to Test PyPI
        run: |
          pip install twine
          twine upload --repository testpypi dist/* -u __token__ -p ${{ secrets.TEST_PYPI_API_TOKEN }}
      - name: Publish distribution 📦 to PyPI
        if: startsWith(github.event.ref, 'refs/tags')
        run: |
          pip install twine
          twine upload dist/* -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}
